services:
  kafka:
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9093

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: pfms
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pritam
    ports:
      - "5432:5432"
    networks:
      - kafka-net
    volumes:
      - postgres_data:/var/lib/postgresql/data

  fastapi:
    build:
      context: ../ # Project root level
      dockerfile: docker/Dockerfile
    container_name: fastapi
    ports:
      - "8000:8000"
    depends_on:
      - kafka
    networks:
      - kafka-net
    restart: always
    environment:
      - KAFKA_SERVER=kafka:9093
      - POSTGRESQLDB_USER=postgres
      - POSTGRESQLDB_PASSWORD=pritam
      - POSTGRESQLDB_HOST=postgres
      - POSTGRESQLDB_PORT=5432
      - POSTGRESQLDB_NAME=pfms
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=1440

volumes:
  postgres_data:
