version: '3.8'

services:
  zookeeper:
    image: zookeeper:3.7
    container_name: zookeeper
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    ports:
      - "2181:2181"
    networks:
      - kafka-net
    restart: always

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9093
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9093
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    ports:
      - "9093:9093"
    depends_on:
      - zookeeper
    networks:
      - kafka-net
    restart: always

networks:
  kafka-net:
    driver: bridge

# version: '3.8'

# services:
#   zookeeper:
#     image: zookeeper:3.7
#     container_name: zookeeper
#     environment:
#       - ZOOKEEPER_CLIENT_PORT=2181
#       - ZOOKEEPER_TICK_TIME=2000
#     ports:
#       - "2181:2181"
#     networks:
#       - kafka-net
#     restart: always

#   kafka:
#     image: wurstmeister/kafka:latest
#     container_name: kafka
#     environment:
#       - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9093
#       - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9093
#       - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
#     ports:
#       - "9093:9093"
#     depends_on:
#       - zookeeper
#     networks:
#       - kafka-net
#     restart: always
  
#   postgres:
#     image: postgres:15
#     container_name: postgres
#     restart: always
#     environment:
#       POSTGRES_DB: pfms
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: pritam
#     ports:
#       - "5432:5432"
#     networks:
#       - kafka-net
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

#   fastapi:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     container_name: fastapi
#     ports:
#       - "8000:8000"
#     depends_on:
#       - kafka
#     networks:
#       - kafka-net
#     restart: always
#     environment:
#       - KAFKA_SERVER=kafka:9093  # use Docker network hostname
#       - POSTGRESQLDB_USER=postgres
#       - POSTGRESQLDB_PASSWORD=pritam
#       - POSTGRESQLDB_HOST=postgres
#       - POSTGRESQLDB_PORT=5432
#       - POSTGRESQLDB_NAME=pfms

# networks:
#   kafka-net:
#     driver: bridge

# volumes:
#   postgres_data: